# Dockerfile for LemonLDAP::NG
# Installation of trunk version of LL::NG

# Start from Debian Jessie
FROM debian:jessie
MAINTAINER Xavier Guimard

# Change SSO DOMAIN here
ENV SSODOMAIN example.com

# Update system and install LL::NG dependencies
RUN apt-get -y update && apt-get -y upgrade && \
apt-get -y install nginx-extras supervisor libapache-session-perl libnet-ldap-perl \
	libcache-cache-perl libdbi-perl perl-modules libwww-perl libcache-cache-perl \
	libxml-simple-perl  libsoap-lite-perl libhtml-template-perl \
	libregexp-assemble-perl libjs-jquery libxml-libxml-perl libcrypt-rijndael-perl \
	libio-string-perl libxml-libxslt-perl libconfig-inifiles-perl libjson-perl \
	libstring-random-perl libemail-date-format-perl libmime-lite-perl \
	libcrypt-openssl-rsa-perl libdigest-hmac-perl libclone-perl libauthen-sasl-perl \
	libnet-cidr-lite-perl libcrypt-openssl-x509-perl libauthcas-perl libtest-pod-perl \
	libtest-mockobject-perl libauthen-captcha-perl libnet-openid-consumer-perl \
	libnet-openid-server-perl libunicode-string-perl libconvert-pem-perl \
	libmouse-perl libplack-perl libglib-perl liblasso-perl yui-compressor dh-systemd \
	vim subversion make devscripts && \
rm -rf /var/lib/apt/lists/*

# Get trunk version of LL::NG
WORKDIR root
RUN svn co svn://svn.forge.objectweb.org/svnroot/lemonldap/trunk lemonldap

# Install LL::NG
WORKDIR lemonldap
RUN make debian-install-for-nginx && \
rm -rf /tmp/*lemonldap* /root/lemonldap/*

WORKDIR /
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Change SSO Domain
RUN sed -i "s/example\.com/${SSODOMAIN}/g" /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-1.js /var/lib/lemonldap-ng/test/index.pl

# Set debug mode
RUN sed -i "s/logLevel\s*=\s*warn/logLevel = debug/" /etc/lemonldap-ng/lemonldap-ng.ini

# Enable sites
RUN cd /etc/nginx/sites-enabled && ln -s ../sites-available/portal-nginx.conf && ln -s ../sites-available/manager-nginx.conf  && ln -s ../sites-available/handler-nginx.conf && ln -s ../sites-available/test-nginx.conf

# Set HTTP header Auth-User
RUN sed -i 's/#auth_request_set/auth_request_set/' /etc/lemonldap-ng/test-nginx.conf
RUN sed -i 's/#fastcgi_param/fastcgi_param/' /etc/lemonldap-ng/test-nginx.conf

# No daemon
RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf

EXPOSE 80 443
VOLUME ["/var/log/nginx", "/etc/apache2", "/etc/lemonldap-ng", "/var/lib/lemonldap-ng/conf", "/var/lib/lemonldap-ng/sessions", "/var/lib/lemonldap-ng/psessions"]
ENTRYPOINT ["/usr/bin/supervisord"]
